openapi: 3.0.3
info:
  title: Task Management
  description: |-
    Ini adalah dokumentasi dari Task Management API
  termsOfService: https://localhost:8080/bagaskara_restful/
  contact:
    email: bagaskara_dwi_putra@teknokrat.ac.id
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://localhost:8080/bagaskara_restful/
tags:
  - name: TaskCategories
    description: Everything about your Task Categories
    externalDocs:
      description: Find out more
      url: https://localhost:8080/bagaskara_restful/
  - name: Tasks
    description: Everything about your Tasks
    externalDocs:
      description: Find out more
      url: https://localhost:8080/bagaskara_restful/
paths:
  /TaskCategories:
    put:
      tags:
        - TaskCategories
      summary: Update a Task Categories
      description: Update a Task Categories
      operationId: index_put
      requestBody:
        description: Update an existent Task Categories in Task Management
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCategories'
          application/xml:
            schema:
              $ref: '#/components/schemas/TaskCategories'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TaskCategories'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCategories'          
            application/xml:
              schema:
                $ref: '#/components/schemas/TaskCategories'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
    post:
      tags:
        - TaskCategories
      summary: Add a new Task Categories to Task Management
      description: Add a new Task Categories
      operationId: index_post
      requestBody:
        description: Create a new Task Categories
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCategories'
          application/xml:
            schema:
              $ref: '#/components/schemas/TaskCategories'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TaskCategories'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCategories'          
            application/xml:
              schema:
                $ref: '#/components/schemas/TaskCategories'
        '405':
          description: Invalid input
    get:
      tags:
        - TaskCategories
      summary: Finds All Task Categories
      description: Multiple Task Categories values can be provided with comma separated strings
      operationId: index_get
      parameters:
        - name: id
          in: query
          description: ID to filter by
          required: false
          explode: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskCategories'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskCategories'
        '400':
          description: Invalid status value
    delete:
      tags:
        - TaskCategories
      summary: Deletes a Task Categories
      description: delete a Task Categories
      operationId: index_delete
      parameters:
        - name: id
          in: header
          description: Task Categories id deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid pet value
  /Tasks:
    post:
      tags:
        - Tasks
      summary: Add a new Task
      description: Add a new Task 
      requestBody:
        description: Create a new Task 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tasks'
          application/xml:
            schema:
              $ref: '#/components/schemas/Tasks'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tasks'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Tasks'
        '405':
          description: Invalid input
    get:
      tags:
        - Tasks
      summary: Finds All Tasks
      description: Multiple Tasks values can be provided with comma separated strings
      parameters:
        - name: id
          in: query
          description: ID to filter by
          required: false
          explode: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasks'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasks'
        '400':
          description: Invalid status value
    delete:
      tags:
        - Tasks
      summary: Deletes a Task
      description: delete a Task
      parameters:
        - name: id
          in: header
          description: Tasks id deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid pet value
  /Tasks/update:
    post:
      tags:
        - Tasks
      summary: Update a Tasks
      description: Update a Tasks
      requestBody:
        description: Update an existent Task Categories in Task Management
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tasks'
          application/xml:
            schema:
              $ref: '#/components/schemas/Tasks'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tasks'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Tasks'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
components:
  schemas:
    TaskCategories:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name: 
          type: string
          example: PHP
    Tasks:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 10
        category_id:
          type: integer
          format: int64
          example: 2
        title:
          type: string
          example: Belajar PHP OOP
        description:
          type: string
          example: Mengerjakan Tugas PHP OOP
        start_date:
          type: string
          example: 2022-10-31
        finish_date:
          type: string
          example: 2022-11-1
        status:
          type: string
          example: New
        doc_url:
          type: string
          example: http://localhost:8080/bagaskara_restful/assets/images/php.jpg
  